@startuml
top to bottom direction
skinparam packageStyle rectangle

actor Admin
actor Employer
actor Customer

rectangle "Mini Restaurant Management System - Sprint 1" {

    (Authentication)

    ' Sprint 1 use cases
    Admin -- (Manage Users)
    Admin -- (Manage Menu)
    Admin -- (Authentication)

    Employer -- (View Orders)
    Employer -- (View Personal Reports)
    Employer -- (Authentication)

    Customer -- (Browse Menu)
    Customer -- (Place Order)
    Customer -- (Manage Profile)
    Customer -- (Authentication)

    ' include relationships
    (Manage Users) .. (Authentication) : <<include>>
    (Manage Menu) .. (Authentication) : <<include>>
    (View Orders) .. (Authentication) : <<include>>
    (View Personal Reports) .. (Authentication) : <<include>>
    (Browse Menu) .. (Authentication) : <<include>>
    (Place Order) .. (Authentication) : <<include>>
    (Manage Profile) .. (Authentication) : <<include>>
}
@enduml